export type InstallerCommand = "init" | "doctor" | "upgrade" | "uninstall";

export interface InstallerRequest {
  command: InstallerCommand;
  targetDirectory: string;
}

export {
  AGENTS_MANAGED_BLOCK_BEGIN,
  AGENTS_MANAGED_BLOCK_END,
  AgentsConfigMergeError,
  mergeAgentsConfigText,
  planAgentsConfigMerge,
  type AgentsConfigMergeErrorCode,
  type AgentsConfigMergePlan,
} from "./agents-config.js";

export {
  AdaptiveProjectTemplateError,
  DEFAULT_MODULE_SCOPE,
  isModuleScope,
  planAdaptiveProjectTemplates,
  type AdaptiveAndroidModuleConfiguration,
  type AdaptiveAndroidProjectConfiguration,
  type AdaptiveAutomationConfiguration,
  type AdaptiveProjectTemplateErrorCode,
  type AdaptiveProjectTemplateOptions,
  type AdaptiveProjectTemplatePlan,
  type AdaptiveTargetTest,
  type AdaptiveTaskContractExample,
  type GradleVerificationConfiguration,
  type ModuleScope,
} from "./adaptive-templates.js";

export {
  detectAndroidProject,
  type AndroidModuleDetection,
  type AndroidModuleType,
  type AndroidProjectDetection,
  type GradleDsl,
  type GradleWrapperDetection,
} from "./android-project.js";
export {
  INITIAL_WORKTREE_ALLOWLIST_CONTENT,
  ProjectInitializationError,
  WORKTREE_ALLOWLIST_RELATIVE_PATH,
  formatProjectInitializationResult,
  planProjectInitialization,
  planProjectResourceInputs,
  runInitProcess,
  runProjectInitialization,
  verifyInitializedProject,
  type InitProcessOptions,
  type InitProcessRunner,
  type InitVerificationCheck,
  type InitVerificationReport,
  type InitVerificationStatus,
  type ProjectInitializationErrorCode,
  type ProjectInitializationOptions,
  type ProjectInitializationPlan,
  type ProjectInitializationResult,
  type ProjectResourceInputPlan,
  type WorktreeAllowlistInitializationStatus,
} from "./init.js";
export {
  INSTALLATION_BACKUPS_DIRECTORY,
  INSTALLATION_CONTROL_DIRECTORY,
  INSTALLATION_HISTORY_DIRECTORY,
  INSTALLATION_MANIFEST_RELATIVE_PATH,
  INSTALLATION_MANIFEST_SCHEMA_VERSION,
  InstallationManifestError,
  applyInstallationPlan,
  completeInstallationManifest,
  detectInstallationConflicts,
  planInstallationPreparation,
  prepareInstallationBackup,
  readInstallationManifest,
  rollbackPreparedInstallation,
  verifyInstallationIntegrity,
  type AppliedInstallation,
  type InstallationApplyOptions,
  type InstallationCompletionOptions,
  type InstallationConflictKind,
  type InstallationConflictReport,
  type InstallationFileConflict,
  type InstallationFileInput,
  type InstallationFileStrategy,
  type InstallationIntegrityCheck,
  type InstallationIntegrityReport,
  type InstallationIntegrityStatus,
  type InstallationManifest,
  type InstallationManifestErrorCode,
  type InstallationManifestFile,
  type InstallationManifestState,
  type InstallationPreparationOptions,
  type InstallationPreparationPlan,
  type InstallationRollbackOptions,
  type PlannedInstallationFile,
  type PreparedInstallation,
  type PreviousInstallationFile,
} from "./install-manifest.js";
export {
  UPGRADE_MARKER_RELATIVE_PATH,
  UPGRADE_RECOVERY_DIRECTORY,
  ProjectUpgradeError,
  applyProjectUpgrade,
  formatProjectUpgradeResult,
  planProjectUpgrade,
  runProjectUpgrade,
  type AppliedProjectUpgrade,
  type PlannedUpgradeFile,
  type PlannedUpgradeRemoval,
  type ProjectUpgradeErrorCode,
  type ProjectUpgradeOptions,
  type ProjectUpgradePlan,
  type ProjectUpgradeResult,
  type UpgradeFileSnapshot,
} from "./upgrade.js";
export {
  UNINSTALL_MARKER_RELATIVE_PATH,
  UNINSTALL_RECOVERY_DIRECTORY,
  ProjectUninstallError,
  applyProjectUninstall,
  formatProjectUninstallResult,
  planProjectUninstall,
  runProjectUninstall,
  type AppliedProjectUninstall,
  type PlannedUninstallFile,
  type ProjectUninstallErrorCode,
  type ProjectUninstallOptions,
  type ProjectUninstallPlan,
  type ProjectUninstallResult,
  type UninstallFileDisposition,
  type UninstallFileSnapshot,
} from "./uninstall.js";
export {
  ORCHESTRATOR_PACKAGE_NAME,
  ORCHESTRATOR_PACKAGE_VERSION,
  ORCHESTRATOR_PLUGIN_REFERENCE,
  OPENCODE_CONFIG_SCHEMA_URL,
  REQUIRED_PLUGIN_REFERENCES,
  SUPERPOWERS_PLUGIN_REFERENCE,
  OpenCodeConfigMergeError,
  mergeOpenCodeConfigText,
  planOpenCodeConfigMerge,
  pluginPackageIdentity,
  type OpenCodeConfigMergeErrorCode,
  type OpenCodeConfigMergeOptions,
  type OpenCodeConfigMergePlan,
  type OpenCodeConfigMergeResult,
} from "./opencode-config.js";
