export {
  AndroidOrchestratorPlugin,
  ORCHESTRATOR_DIRECTORY_ENV,
  ORCHESTRATOR_WORKTREE_ENV,
  createCompatiblePlugin,
  default,
} from "./plugin/index.js";
export {
  COMMON_HOOK_NAMES,
  COMMON_PLUGIN_INPUT_KEYS,
  defineCompatibleHooks,
  toCompatiblePluginInput,
  type CommonHookName,
  type CommonPluginInputKey,
  type CompatibleHooks,
  type CompatiblePlugin,
  type CompatiblePluginInput,
} from "./compatibility/hooks.js";
export {
  ORCHESTRATOR_DOCTOR_TOOL_NAME,
  ORCHESTRATOR_STATUS_TOOL_NAME,
  READ_ONLY_TOOL_NAMES,
  ReadOnlyToolError,
  createReadOnlyTools,
  type DoctorRunner,
  type InstallationCheckRunner,
  type ReadOnlyToolErrorCode,
  type ReadOnlyToolName,
  type ReadOnlyTools,
  type ReadOnlyToolsOptions,
  type StatusRunner,
  type StatusRunnerInput,
  type StatusRunnerResult,
} from "./tools/index.js";
export {
  CERTIFIED_OPENCODE_VERSIONS,
  MAXIMUM_OPENCODE_VERSION,
  MINIMUM_OPENCODE_VERSION,
  checkOpenCodeVersion,
  compareSemanticVersions,
  parseOpenCodeVersion,
  type OpenCodeVersionCheck,
  type OpenCodeVersionSupport,
  type ParsedSemanticVersion,
} from "./compatibility/versions.js";
export {
  EXPECTED_MANAGED_FILE_COUNT,
  formatDoctorReport,
  inspectAndroidSdk,
  inspectOpenCode,
  inspectRequiredCommands,
  installationDoctorChecks,
  runCommand,
  runDoctor,
  type CommandResult,
  type CommandRunner,
  type DoctorCheck,
  type DoctorCheckStatus,
  type DoctorOptions,
  type DoctorReport,
} from "./doctor/index.js";
export {
  AGENTS_MANAGED_BLOCK_BEGIN,
  AGENTS_MANAGED_BLOCK_END,
  AgentsConfigMergeError,
  mergeAgentsConfigText,
  planAgentsConfigMerge,
  type AgentsConfigMergeErrorCode,
  type AgentsConfigMergePlan,
} from "./installer/agents-config.js";
export {
  AdaptiveProjectTemplateError,
  DEFAULT_MODULE_SCOPE,
  isModuleScope,
  planAdaptiveProjectTemplates,
  type AdaptiveAndroidModuleConfiguration,
  type AdaptiveAndroidProjectConfiguration,
  type AdaptiveAutomationConfiguration,
  type AdaptiveProjectTemplateErrorCode,
  type AdaptiveProjectTemplateOptions,
  type AdaptiveProjectTemplatePlan,
  type AdaptiveTaskContractExample,
  type GradleVerificationConfiguration,
  type ModuleScope,
} from "./installer/adaptive-templates.js";
export {
  detectAndroidProject,
  type AndroidModuleDetection,
  type AndroidModuleType,
  type AndroidProjectDetection,
  type GradleDsl,
  type GradleWrapperDetection,
} from "./installer/android-project.js";
export {
  GRADLE_TASK_DISCOVERY_INIT_SCRIPT,
  GradleVerificationDiscoveryError,
  discoverGradleVerificationConfiguration,
  inferGradleVerificationConfiguration,
  parseGradleTaskPaths,
  type GradleVerificationDiscoveryErrorCode,
  type GradleVerificationDiscoveryOptions,
  type GradleVerificationProcessOptions,
  type GradleVerificationProcessRunner,
} from "./installer/gradle-verification.js";
export {
  INITIAL_WORKTREE_ALLOWLIST_CONTENT,
  ProjectInitializationError,
  WORKTREE_ALLOWLIST_RELATIVE_PATH,
  formatProjectInitializationResult,
  planProjectInitialization,
  planProjectResourceInputs,
  runInitProcess,
  runProjectInitialization,
  verifyInitializedProject,
  type InitProcessOptions,
  type InitProcessRunner,
  type InitVerificationCheck,
  type InitVerificationReport,
  type InitVerificationStatus,
  type ProjectInitializationErrorCode,
  type ProjectInitializationOptions,
  type ProjectInitializationPlan,
  type ProjectInitializationResult,
  type ProjectResourceInputPlan,
  type WorktreeAllowlistInitializationStatus,
} from "./installer/init.js";
export {
  INSTALLATION_BACKUPS_DIRECTORY,
  INSTALLATION_CONTROL_DIRECTORY,
  INSTALLATION_HISTORY_DIRECTORY,
  INSTALLATION_MANIFEST_RELATIVE_PATH,
  INSTALLATION_MANIFEST_SCHEMA_VERSION,
  InstallationManifestError,
  applyInstallationPlan,
  completeInstallationManifest,
  detectInstallationConflicts,
  planInstallationPreparation,
  prepareInstallationBackup,
  readInstallationManifest,
  rollbackPreparedInstallation,
  verifyInstallationIntegrity,
  type AppliedInstallation,
  type InstallationApplyOptions,
  type InstallationCompletionOptions,
  type InstallationConflictKind,
  type InstallationConflictReport,
  type InstallationFileConflict,
  type InstallationFileInput,
  type InstallationFileStrategy,
  type InstallationIntegrityCheck,
  type InstallationIntegrityReport,
  type InstallationIntegrityStatus,
  type InstallationManifest,
  type InstallationManifestErrorCode,
  type InstallationManifestFile,
  type InstallationManifestState,
  type InstallationPreparationOptions,
  type InstallationPreparationPlan,
  type InstallationRollbackOptions,
  type PlannedInstallationFile,
  type PreparedInstallation,
  type PreviousInstallationFile,
} from "./installer/install-manifest.js";
export {
  UPGRADE_MARKER_RELATIVE_PATH,
  UPGRADE_RECOVERY_DIRECTORY,
  ProjectUpgradeError,
  applyProjectUpgrade,
  formatProjectUpgradeResult,
  planProjectUpgrade,
  runProjectUpgrade,
  type AppliedProjectUpgrade,
  type PlannedUpgradeFile,
  type PlannedUpgradeRemoval,
  type ProjectUpgradeErrorCode,
  type ProjectUpgradeOptions,
  type ProjectUpgradePlan,
  type ProjectUpgradeResult,
  type UpgradeFileSnapshot,
} from "./installer/upgrade.js";
export {
  UNINSTALL_MARKER_RELATIVE_PATH,
  UNINSTALL_RECOVERY_DIRECTORY,
  ProjectUninstallError,
  applyProjectUninstall,
  formatProjectUninstallResult,
  planProjectUninstall,
  runProjectUninstall,
  type AppliedProjectUninstall,
  type PlannedUninstallFile,
  type ProjectUninstallErrorCode,
  type ProjectUninstallOptions,
  type ProjectUninstallPlan,
  type ProjectUninstallResult,
  type UninstallFileDisposition,
  type UninstallFileSnapshot,
} from "./installer/uninstall.js";
export {
  ORCHESTRATOR_PACKAGE_NAME,
  ORCHESTRATOR_PACKAGE_VERSION,
  ORCHESTRATOR_PLUGIN_REFERENCE,
  OPENCODE_CONFIG_SCHEMA_URL,
  REQUIRED_PLUGIN_REFERENCES,
  SUPERPOWERS_PLUGIN_REFERENCE,
  OpenCodeConfigMergeError,
  mergeOpenCodeConfigText,
  planOpenCodeConfigMerge,
  pluginPackageIdentity,
  type OpenCodeConfigMergeErrorCode,
  type OpenCodeConfigMergeOptions,
  type OpenCodeConfigMergePlan,
  type OpenCodeConfigMergeResult,
} from "./installer/opencode-config.js";
